[package]
name = "fixie-trie"
version = "0.2.0"
authors = ["Julian Squires <julian@cipht.net>"]
publish = false

[features]
i128 = ["quickcheck/i128", "rand/i128_support"]

[dependencies]

[dev-dependencies]
quickcheck = "0.6"
rand = "0.4"
qp-trie = "0.7.1"